name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: pnpm install

      - name: Test
        run: pnpm run test
  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: pnpm install

      - name: Format
        run: pnpm run format
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Prettier
        run: |
          echo "module.exports = require('@lobehub/lint').prettier;" >> .prettierrc.js
          pnpm run prettier

      - name: Commit changes
        run: |
          git config user.name "lobehubbot"
          git config user.email "i@lobehub.com"
          git add .
          git commit -m "🤖 chore: Auto format json files"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}